name: "Install a binary from GitHub releases"
description: "Install binaries from GitHub releases"
author: "Lee Briggs"
inputs:
  repo:
    description: "GitHub repo where binary is located"
    required: true
  tag:
    description: "tag containing binary to install"
    default: latest
    required: true
  fileRegexp:
    description: "the regexp to match the filename of the release to download"
    required: false
branding:
  icon: 'archive'  
  color: 'green'
runs:
  using: 'node12'
  main: 'lib/main.js'
