name: "Install a binary from GitHub releases"
description: "Install binaries from GitHub releases"
author: "Lee Briggs"
inputs:
  token:
    description: 'GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)'
    default: ${{ github.token }}
  repo:
    description: "GitHub repo where binary is located"
    required: true
  tag:
    description: "tag containing binary to install"
    default: latest
    required: true
  digest:
    description: "SHA256 digest of the release asset. Specify this parameter to verify the integrity of the downloaded asset."
    required: false
  prerelease:
    description: "Consider prerelease for latest tag"
    default: "false"
    required: false
  platform:
    description: "OS Platform to match in release package. Specify this parameter if the repository releases do not follow a normal convention otherwise it will be auto-detected."
    required: false
  arch:
    description: "OS Architecture to match in release package. Specify this parameter if the repository releases do not follow a normal convention otherwise it will be auto-detected."
    required: false
  extension:
    description: "Custom file extension to match in release package.  Specify this parameter if the repository releases do not provide a .tar.gz or .zip format release."
    required: false
  extension-matching:
    description: "Enable/disable file extension matching in release package.  Specify this parameter if the repository releases do not have a file extension e.g. they are pure binaries."
    required: false
    default: enable
  rename-to:
    description: "When installing a release that is not an archive, e.g. a pure binary, this controls how the downloaded release asset is renamed.  Specify this parameter if installing a non-archive release."
    required: false
  chmod:
    description: "When installing a release that is not an archive, e.g. a pure binary, this controls how the downloaded release asset is chmod'd.  Specify this parameter if installing a non-archive release and you need to change its permissions e.g. make it executable."
    required: false
  cache:
    description: "When set to 'enable', caches the downloads of known tags with actions/cache"
    required: false
  binaries-location:
    description: "Specify this parameter if the binaries are not located in the root of the release archive. The parameter should be a relative path to the release archive. For example, if the binaries are located in the 'bin' directory of the release archive, the parameter should be 'bin'."
    required: false
  asset-name:
    description: "Use this parameter to specify the name of the asset to download if the repo has multiple assets."
    required: false
branding:
  icon: "archive"
  color: "green"
runs:
  using: "node20"
  main: "lib/main.js"
