name: "Install a binary from GitHub releases"
description: "Install binaries from GitHub releases"
author: "Lee Briggs"
inputs:
  repo:
    description: "GitHub repo where binary is located"
    required: true
  tag:
    description: "tag containing binary to install"
    default: latest
    required: true
  platform:
    description: "OS Platform to match in release package. Specify this parameter if the repository releases do not follow a normal convention otherwise it will be auto-detected."
    required: false
  arch:
    description: "OS Architecture to match in release package. Specify this parameter if the repository releases do not follow a normal convention otherwise it will be auto-detected."
    required: false
  cache:
    description: "When set to 'enable', caches the downloads of known tags with actions/cache"
    required: false
branding:
  icon: "archive"
  color: "green"
runs:
  using: "node12"
  main: "lib/main.js"
