name: "Test installation of pulumictl"

on:
  pull_request:
    paths-ignore:
      - 'CHANGELOG.md'

jobs:
  test-install:
    runs-on: ubuntu-latest
    steps:
      - name: Install pulumictl
        uses: t0yv0/action-install-gh-release@v1.7.0
        with:
          repo: pulumi/pulumictl
          tag: v0.0.31
      - run: |
          pulumictl get version
